# Generated by Django 5.0.3 on 2024-08-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('code', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('name_short', models.TextField(blank=True, null=True)),
                ('name_tv', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('country_full', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('nationality_full', models.TextField(blank=True, null=True)),
                ('nationality_code', models.TextField(blank=True, null=True)),
                ('height', models.BigIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=38, null=True)),
                ('disciplines', models.TextField(blank=True, null=True)),
                ('events', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.TextField(blank=True, null=True)),
                ('birth_country', models.TextField(blank=True, null=True)),
                ('residence_place', models.TextField(blank=True, null=True)),
                ('residence_country', models.TextField(blank=True, null=True)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('lang', models.TextField(blank=True, null=True)),
                ('coach', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('hero', models.TextField(blank=True, null=True)),
                ('influence', models.TextField(blank=True, null=True)),
                ('philosophy', models.TextField(blank=True, null=True)),
                ('sporting_relatives', models.TextField(blank=True, null=True)),
                ('ritual', models.TextField(blank=True, null=True)),
                ('other_sports', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'athletes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('tag', models.TextField(blank=True, null=True)),
                ('sport', models.TextField(blank=True, null=True)),
                ('sport_code', models.TextField(blank=True, null=True)),
                ('sport_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medallists',
            fields=[
                ('code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('medal_date', models.DateField(blank=True, null=True)),
                ('medal_type', models.TextField(blank=True, null=True)),
                ('medal_code', models.BigIntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('team_gender', models.TextField(blank=True, null=True)),
                ('discipline', models.TextField(blank=True, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('event_type', models.TextField(blank=True, null=True)),
                ('url_event', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medallists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('medal_type', models.TextField(blank=True, null=True)),
                ('medal_code', models.BigIntegerField(blank=True, null=True)),
                ('medal_date', models.DateField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('discipline', models.TextField(blank=True, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('event_type', models.TextField(blank=True, null=True)),
                ('url_event', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedalsTotal',
            fields=[
                ('country_code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('gold_medal', models.BigIntegerField(blank=True, null=True)),
                ('silver_medal', models.BigIntegerField(blank=True, null=True)),
                ('bronze_medal', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medals_total',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('team', models.TextField(blank=True, null=True)),
                ('team_gender', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('country_full', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('discipline', models.TextField(blank=True, null=True)),
                ('disciplines_code', models.TextField(blank=True, null=True)),
                ('events', models.TextField(blank=True, null=True)),
                ('athletes', models.TextField(blank=True, null=True)),
                ('coaches', models.TextField(blank=True, null=True)),
                ('athletes_codes', models.TextField(blank=True, null=True)),
                ('num_athletes', models.DecimalField(blank=True, decimal_places=1, max_digits=38, null=True)),
                ('coaches_codes', models.TextField(blank=True, null=True)),
                ('num_coaches', models.DecimalField(blank=True, decimal_places=1, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TorchRoute',
            fields=[
                ('title', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('stage_number', models.DecimalField(blank=True, decimal_places=1, max_digits=38, null=True)),
            ],
            options={
                'db_table': 'torch_route',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('venue', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('sports', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venues',
                'managed': True,
            },
        ),
    ]
