# Generated by Django 5.0.3 on 2024-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympics_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalsTally',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('edition', models.TextField(blank=True, null=True)),
                ('edition_id', models.BigIntegerField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('country_noc', models.TextField(blank=True, null=True)),
                ('gold', models.BigIntegerField(blank=True, null=True)),
                ('silver', models.BigIntegerField(blank=True, null=True)),
                ('bronze', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medals_tally',
                'managed': False,
            },
        ),
    ]
